apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: app
  namespace: flux-system
spec:
  image: registry.jimmyding.com/app
  interval: 5m
  secretRef:
    name: registry-credential
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app
  policy:
    semver:
      range: ">= 0.0.0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: app-serviceaccount
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  # TODO: increase this when i figure out how to make elixir pods communicate with each other
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-serviceaccount
      containers:
        - name: app
          image: registry.jimmyding.com/app:0.1.3 # {"$imagepolicy": "flux-system:app"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-secret-key
                  key: SECRET_KEY_BASE
            - name: PHX_HOST
              value: jimmyding.com
      imagePullSecrets:
        - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: app-staging
  namespace: flux-system
spec:
  image: registry.jimmyding.com/app-staging
  interval: 5m
  secretRef:
    name: registry-credential
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: app-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app-staging
  filterTags:
    pattern: ^.+-[a-f0-9]{8}-(?P<ts>\d{4}-\d{2}-\d{2}_\d{2}\.\d{2}\.\d{2})$
    extract: $ts
  policy:
    alphabetical:
      order: asc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: staging
subjects:
- kind: ServiceAccount
  name: app-serviceaccount
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-serviceaccount
      containers:
        - name: app
          image: registry.jimmyding.com/app-staging:main-c3d48cde-2024-03-06_21.12.26 # {"$imagepolicy": "flux-system:app-staging"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-secret-key
                  key: SECRET_KEY_BASE
            - name: PHX_HOST
              value: staging.jimmyding.com
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
        - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-staging
  namespace: staging
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
