---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: arc-repo
  namespace: arc-system
spec:
  type: oci
  interval: 1m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-release
  namespace: arc-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc-repo
      version: 0.8.2
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-release
  namespace: arc-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc-repo
      version: 0.8.2
  interval: 1m0s
  values:
    githubConfigUrl: https://github.com/DimmyJing/personal
    githubConfigSecret: pre-defined-secret
    minRunners: 1
    containerMode:
      type: dind
