---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pv-claim
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: docker-registry-repo
  namespace: docker-registry
spec:
  interval: 1m0s
  url: https://helm.twun.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: docker-registry-release
  namespace: docker-registry
spec:
  chart:
    spec:
      chart: docker-registry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: docker-registry-repo
      version: 2.2.2
  interval: 1m0s
  values:
    replicaCount: 1
    persistence:
      enabled: true
      size: 20Gi
      deleteEnabled: true
      storageClass: longhorn
      existingClaim: docker-registry-pv-claim
    secrets:
      htpasswd: admin:$2y$05$Ozhlsk1f.wVcjA83YjGL3OwBjiWcf2iBFPMqJK/p6z6/kzGDxAvt.
    configData:
      notifications:
        endpoints:
          - name: flux-webhook
            url: https://flux-webhook.jimmyding.com/hook/3f56c1d033c477d153a426c4f99901a8d60b8526b22c69067e6c2272416ffb65
            timeout: 500ms
            threshold: 5
            backoff: 1s
    garbageCollect:
      enabled: true
    extraEnvVars:
      - name: REGISTRY_STORAGE_DELETE_ENABLED
        value: "true"
