---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pv-claim
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: docker-registry-repo
  namespace: docker-registry
spec:
  interval: 1m0s
  url: https://helm.twun.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: docker-registry-release
  namespace: docker-registry
spec:
  chart:
    spec:
      chart: docker-registry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: docker-registry-repo
      version: 2.2.2
  interval: 1m0s
  values:
    replicaCount: 1
    persistence:
      enabled: true
      size: 20Gi
      deleteEnabled: true
      storageClass: longhorn
      existingClaim: docker-registry-pv-claim
    secrets:
      htpasswd: admin:$2y$05$Ozhlsk1f.wVcjA83YjGL3OwBjiWcf2iBFPMqJK/p6z6/kzGDxAvt.
