---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-repo
  namespace: minio-system
spec:
  type: oci
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio-release
  namespace: minio-system
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-repo
      version: 13.6.4
  interval: 1m0s
  values:
    auth:
      existingSecret: minio-secret
    mode: distributed
    persistence:
      storageClass: longhorn
      size: 20Gi
