apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web
  namespace: flux-system
spec:
  image: registry.jimmyding.com/web
  interval: 5m
  secretRef:
    name: registry-credential
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web
  policy:
    semver:
      range: ">= 0.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: registry.jimmyding.com/web:0.1.2 # {"$imagepolicy": "flux-system:web"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web-staging
  namespace: flux-system
spec:
  image: registry.jimmyding.com/web-staging
  interval: 5m
  secretRef:
    name: registry-credential
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web-staging
  filterTags:
    pattern: ^.+-[a-f0-9]{8}-(?P<ts>\d{4}-\d{2}-\d{2}_\d{2}\.\d{2}\.\d{2})$
    extract: $ts
  policy:
    alphabetical:
      order: asc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-staging
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: registry.jimmyding.com/web-staging:main-76f6096d-2024-03-06_18.18.57 # {"$imagepolicy": "flux-system:web-staging"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-secret-key
                  key: SECRET_KEY_BASE
      imagePullSecrets:
        - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-staging
  namespace: staging
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
