name: Build web for staging and push to registry
on:
  push:
    branches:
      - main
    paths:
      - web/**
  pull_request:
    branches:
      - main
    paths:
      - web/**
  workflow_dispatch:
jobs:
  build-web-staging:
    runs-on: arc-runner-release
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y unzip
      - id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%F_%H.%M.%S)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: rm -rf ./node_modules
      - run: bun install --production --frozen-lockfile
      - run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u admin --password-stdin registry.jimmyding.com
      - run: docker build -t registry.jimmyding.com/web:${{ steps.prep.outputs.BUILD_ID }} . -f ../build/web.dockerfile
      - run: docker push registry.jimmyding.com/web:${{ steps.prep.outputs.BUILD_ID }}
