name: Build app for production and push to registry
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of the release in the format of v1.0.0
jobs:
  build-app-production:
    runs-on: arc-runner-release
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - id: prep
        run: |
          TAG=${{ github.event.release.tag_name || github.event.inputs.version }}
          echo "BUILD_ID=${TAG#v}" >> $GITHUB_OUTPUT
      - run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u admin --password-stdin registry.jimmyding.com
      - run: docker build -t registry.jimmyding.com/app:${{ steps.prep.outputs.BUILD_ID }} .
      - run: docker push registry.jimmyding.com/app:${{ steps.prep.outputs.BUILD_ID }}
