name: Build web for staging and push to registry
on:
  push:
    branches:
      - main
    paths:
      - app/**
  pull_request:
    branches:
      - main
    paths:
      - app/**
  workflow_dispatch:
jobs:
  build-web-staging:
    runs-on: arc-runner-release
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y unzip git
      - id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%F_%H.%M.%S)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2.2"
          elixir-version: "1.16.1"
          install-hex: true
          install-rebar: false
      - run: mix deps.get --only prod
        env:
          ELIXIR_ERL_OPTIONS: +fnu
      - run: MIX_ENV=prod mix compile
      - run: MIX_ENV=prod mix assets.deploy
      - run: mix phx.gen.release
      - run: MIX_ENV=prod mix release
      - run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u admin --password-stdin registry.jimmyding.com
      - run: docker build -t registry.jimmyding.com/web-staging:${{ steps.prep.outputs.BUILD_ID }} . -f ../build/web.dockerfile
      - run: docker push registry.jimmyding.com/web-staging:${{ steps.prep.outputs.BUILD_ID }}
