name: Build app for staging and push to registry
on:
  push:
    branches:
      - main
    paths:
      - app/**
  pull_request:
    branches:
      - main
    paths:
      - app/**
  workflow_dispatch:
jobs:
  build-app-staging:
    runs-on: arc-runner-release
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%F_%H.%M.%S)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
      - run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u admin --password-stdin registry.jimmyding.com
      - run: docker build -t registry.jimmyding.com/app-staging:${{ steps.prep.outputs.BUILD_ID }} .
      - run: docker push registry.jimmyding.com/app-staging:${{ steps.prep.outputs.BUILD_ID }}
